### ISSUE TITLE
"RuntimeError: Cannot modify ReadOnlyDict" after upgrade to 2023.6.1

### ISSUE THREAD

**Issue by 303Bryan** [Breina/ha-artnet-led#34]
I am running into issues since upgrading to 2023.6.1, logs are below. 

Current version:
Home Assistant 2023.6.1
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230608.0 - latest

```
Logger: homeassistant.components.light
Source: helpers/storage.py:122
Integration: Light (documentation, issues)
First occurred: 8:43:44 PM (2 occurrences)
Last logged: 8:43:44 PM

Error while setting up artnet_led platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/artnet_led/light.py", line 146, in async_setup_platform
    await entity_registry.async_load()
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 952, in async_load
    data = await self._store.async_load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 122, in async_load
    return await self._load_task
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Cannot modify ReadOnlyDict
```

**Comment by 303Bryan** [comment]
Quick update: Removing and reinstalling the integration resolves the issue.

**Comment by Breina** [comment]
Fixed
