### ISSUE TITLE
Invalid color modes

### ISSUE THREAD

**Issue by Robotron80** [Breina/ha-artnet-led#56]
Since update to Home Assistant 2024.3 I've got some issues with ha-artnet-led integration.
I can control the single entities I've configured in configuration.yaml. When I add one of those entities in a lighting group, this group gets unavailable.

In the Home Assistant log file I've found following error for every artnet-entity:
2024-03-12 14:48:21.339 WARNING (MainThread) [homeassistant.components.light] light.empf_licht_tube_1 (<class 'custom_components.artnet_led.light.DmxWhite'>) sets invalid supported color modes {<ColorMode.WHITE: 'white'>, <ColorMode.COLOR_TEMP: 'color_temp'>}, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/Breina/ha-artnet-led/issues

**Comment by abvaden** [comment]
I am having this same issue as well here are a little more logs if it helps.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 865, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1327, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/group/__init__.py", line 497, in async_added_to_hass
    self.async_on_remove(start.async_at_start(self.hass, self._update_at_start))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/start.py", line 67, in async_at_start
    return _async_at_core_state(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/start.py", line 32, in _async_at_core_state
    hass.async_run_hass_job(at_start_job, hass)
  File "/usr/src/homeassistant/homeassistant/core.py", line 727, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/group/__init__.py", line 502, in _update_at_start
    self.async_update_group_state()
  File "/usr/src/homeassistant/homeassistant/components/group/light.py", line 274, in async_update_group_state
    supported_color_modes = filter_supported_color_modes(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 134, in filter_supported_color_modes
    raise HomeAssistantError
homeassistant.exceptions.HomeAssistantError

**Comment by Breina** [comment]
Alright thanks for the report lads. Should be fixed, please verify. :)

https://github.com/Breina/ha-artnet-led/releases/tag/v0.1.21

**Comment by abvaden** [comment]
Working well here!
Thanks for the quick turn around!

**Comment by Robotron80** [comment]
I've just updated the version. Now it's working perfectly.
Thank you for fast fixing!
